### ISSUE TITLE
Pregledanje rada

### ISSUE THREAD

**Issue by djordjeurosevic** [MATF-RG17/RG070-kuristo#1]

**Comment by ivan-cukic-matf** [comment]
Navedite na osnovu kog ste projekta (URL) pravili svoj projekat.

**Comment by djordjeurosevic** [comment]
Nije u pitanju jedan projekat, gledao sam više tutorijala na internetu (gomila subway surfer klonova), i više različitih projekata koje su drugi studenti radili (endless runner žanr je prilično popularan ovih godina) i uglavnom većina ima slične ideje. 
Jedino što se sećam da mi je pomoglo je implementacija staze, tj. ideja sa prethodnim, trenutnim i sledećim skupom blokova.
Ali svaku liniju koda sam sam otkucao i ukoliko je potrebno da bilo šta izmenim ili dodam, zaista mi neće biti problem.

**Comment by ivan-cukic-matf** [comment]
Imate previše sličnosti sa projektom `RG088-maraton`:

Jedna od linija:

 - maraton: `GLfloat height = (G_CONST * max_t * M_PI) / (2 * kuristo.vz);`
 - kuristo: `GLfloat height = (G_CONST * max_t * M_PI) / (2 * avatar.vz);`

F-ja koja sadrži ove linije je skoro ista u oba projekta, samo je kod Vas prevedeno skoro sve na srpski.

Takodje, oredganizacija projekta - `game.c` -> `logika_igre.c` (u kojima je f-ja iznad), `track.c` -> `staza.c` (i, na primer, funkcije `set_seg_ptrs` -> `postavi_pokazivace_blokovi`), `timer.c` -> `timer.c` (imena prom. prevedena na srpski).

**Comment by ivan-cukic-matf** [comment]
Obavestio sam profesorku, tako da je odluka u njenim rukama.

**Comment by djordjeurosevic** [comment]
Važi. Hvala Vam mnogo.

**Comment by ivan-cukic-matf** [comment]
Dogovor je sledeći - možete da izadjete na ispit u petak.

Do 25. 9. morate značajnije da doradite projekat. Obavezno je da redovno komitujete izmene na github.

Poeni sa projekta će se računati podeljeni sa dva. Ocena će Vam biti upisana tek nakon ove dorade.
